version: '3'
services:
  postgres:
    image: "postgres" # use latest official postgres version
    container_name: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - ../db/database.env # configure postgres
    volumes: 
            - ../db/db.dump.sql:/docker-entrypoint-initdb.d/db.dump.sql
    networks:
      - project-network
  
  theaterseating:
    image: "${DOCKER_REGISTRY-}theaterseating"
    ports:
      - "8000:8000"
    build:
      context: ../src
      dockerfile: ../Dockerfile
      args:
        - github_user=
        - github_personal_token=
    links:
      - postgres
    networks:
      - project-network

volumes:
  database-data: # named volumes can be managed easier using docker-compose

networks:
  project-network:
    external: false